# outputs.tf
output "vpc_id" {
  description = "ID of the VPC"
  value       = module.vpc.vpc_id
}

output "vpc_cidr_block" {
  description = "CIDR block of the VPC"
  value       = module.vpc.vpc_cidr_block
}

output "private_subnet_ids" {
  description = "IDs of the private subnets"
  value       = module.vpc.private_subnet_ids
}

output "public_subnet_ids" {
  description = "IDs of the public subnets"
  value       = module.vpc.public_subnet_ids
}

output "cluster_id" {
  description = "EKS cluster ID"
  value       = module.eks.cluster_id
}

output "cluster_arn" {
  description = "EKS cluster ARN"
  value       = module.eks.cluster_arn
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane"
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module"
  value       = module.eks.kubectl_config
  sensitive   = true
}

output "sonarqube_public_ip" {
  description = "Public IP address of SonarQube instance"
  value       = module.sonarqube.public_ip
}

output "sonarqube_private_ip" {
  description = "Private IP address of SonarQube instance"
  value       = module.sonarqube.private_ip
}

output "sonarqube_url" {
  description = "SonarQube URL"
  value       = "http://${module.sonarqube.public_ip}:9000"
}

output "argocd_url" {
  description = "ArgoCD URL (use kubectl port-forward)"
  value       = "https://localhost:8080"
}

output "grafana_url" {
  description = "Grafana URL (use kubectl port-forward)"
  value       = "http://localhost:3000"
}