stages:
  - select

# Selector jobs -> trigger child pipelines
run-app-pipeline:
  stage: select
  script: echo "Triggering App pipeline..."
  rules:
    - when: manual
  trigger:
    include: .gitlab-ci-app.yml
    strategy: depend

run-infra-pipeline:
  stage: select
  script: echo "Triggering Infra pipeline..."
  rules:
    - when: manual
  trigger:
    include: .gitlab-ci-infra.yml
    strategy: depend
