include:
  - local: '.gitlab-ci-app.yml'
  - local: '.gitlab-ci-infra.yml'

stages:
  - select
  - app-build
  - backend-setup
  - infra-validate
  - infra-plan
  - infra-deploy

# Selector jobs
run-app-pipeline:
  stage: select
  script: echo "Triggering App pipeline..."
  rules:
    - when: manual
  variables:
    RUN_APP_PIPELINE: "true"

run-infra-pipeline:
  stage: select
  script: echo "Triggering Infra pipeline..."
  rules:
    - when: manual
  variables:
    RUN_INFRA_PIPELINE: "true"
