stages:
  - select

# Selector job for App
run-app-pipeline:
  stage: select
  rules:
    - when: manual
  trigger:
    include: .gitlab-ci-app.yml
    strategy: depend

# Selector job for Infra
run-infra-pipeline:
  stage: select
  rules:
    - when: manual
  trigger:
    include: .gitlab-ci-infra.yml
    strategy: depend
