trigger_app_pipeline:
  stage: trigger
  script: []
  trigger:
    include: app-pipeline.yml
  rules:
    - when: manual
      allow_failure: false

trigger_infra_pipeline:
  stage: trigger
  script: []
  trigger:
    include: infra-pipeline.yml
  rules:
    - when: manual
      allow_failure: false
