stages:
  - backend-setup
  - infra-initialise
  - infra-validate
  - infra-plan
  - infra-deploy

variables:
  TF_ROOT: ${CI_PROJECT_DIR}/Livrables/infra/main
  BACKEND_ROOT: ${CI_PROJECT_DIR}/Livrables/infra/backend
  TF_STATE_NAME: ${CI_COMMIT_REF_SLUG}
  TF_CACHE_KEY: ${CI_COMMIT_REF_SLUG}
  AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION:-us-east-1}"

.backend-base:
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]

backend-setup:
  stage: backend-setup
  extends: .backend-base
  script:
    - cd ${BACKEND_ROOT}
    - terraform init
    - terraform apply -auto-approve

infra-initialise:
  stage: infra-initialise
  extends: .backend-base
  script:
    - cd $TF_ROOT
    - terraform init -input=false -upgrade
  needs:
    - backend-setup

infra-validate:
  stage: infra-validate
  extends: .backend-base
  script:
    - cd ${TF_ROOT}
    - terraform validate
    - terraform fmt -check
  needs:
    - infra-initialise

infra-plan:
  stage: infra-plan
  extends: .backend-base
  script:
    - cd ${TF_ROOT}
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - ${TF_ROOT}/tfplan
    expire_in: 7 days
  needs:
    - infra-validate

# Last stage: manual apply or destroy
infra-apply:
  stage: infra-deploy
  extends: .backend-base
  script:
    - cd ${TF_ROOT}
    - terraform apply -auto-approve tfplan
  dependencies:
    - infra-plan
  needs:
    - infra-plan
  environment:
    name: production
  rules:
    - when: manual

infra-destroy:
  stage: infra-deploy
  extends: .backend-base
  script:
    - cd ${TF_ROOT}
    - terraform destroy -auto-approve
  environment:
    name: production
    action: stop
  rules:
    - when: manual
