stages:
  - infra-validate
  - infra-plan
  - infra-deploy

variables:
  TF_ROOT: ${CI_PROJECT_DIR}/Livrables/infra
  TF_STATE_NAME: ${CI_COMMIT_REF_SLUG}
  TF_CACHE_KEY: ${CI_COMMIT_REF_SLUG}
  AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION:-us-east-1}"

.terraform-base:
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  cache:
    key: "${TF_CACHE_KEY}"
    paths:
      - ${TF_ROOT}/.terraform
      - ${TF_ROOT}/.terraform.lock.hcl
  before_script:
    - cd ${TF_ROOT}
    - apk add --no-cache python3 py3-pip curl unzip
    - pip3 install awscli
    - aws --version

infra-validate:
  stage: infra-validate
  extends: .terraform-base
  cache:
    key: terraform
    paths:
      - ${TF_ROOT}/.terraform
      - ${TF_ROOT}/.terraform.lock.hcl
  script:
    - terraform init -reconfigure
    - terraform validate
    - terraform fmt -check

infra-plan:
  stage: infra-plan
  extends: .terraform-base
  cache:
    key: terraform
    paths:
      - ${TF_ROOT}/.terraform
      - ${TF_ROOT}/.terraform.lock.hcl
  script:
    - terraform init -reconfigure
    - terraform plan -input=false -out=tfplan
    - terraform show -json tfplan > tfplan.json
  artifacts:
    name: terraform-plan-${CI_COMMIT_SHORT_SHA}
    paths:
      - ${TF_ROOT}/tfplan
      - ${TF_ROOT}/tfplan.json
    expire_in: 7 days
    reports:
      terraform: ${TF_ROOT}/tfplan.json
  needs:
    - job: infra-validate
      artifacts: true

# Show current state for debugging
infra-show-state:
  stage: infra-plan
  extends: .terraform-base
  script:
    - echo "=== Current Terraform State ==="
    - terraform show
    - echo "=== State List ==="
    - terraform state list || echo "No state found"
    - terraform init -reconfigure
  allow_failure: true

# Last stage: manual apply or destroy
infra-apply:
  stage: infra-deploy
  cache:
    key: terraform
    paths:
      - ${TF_ROOT}/.terraform
      - ${TF_ROOT}/.terraform.lock.hcl
  extends: .terraform-base
  script:
    - terraform apply -auto-approve tfplan
    - echo "=== Resources Created ==="
    - terraform state list
  dependencies:
    - infra-plan
  needs:
  - job: infra-plan
    artifacts: true
    optional: true

  environment:
    name: production
  rules:
    - when: manual

infra-destroy:
  stage: infra-deploy
  extends: .terraform-base
  cache:
    key: terraform
    paths:
      - ${TF_ROOT}/.terraform
      - ${TF_ROOT}/.terraform.lock.hcl
  script:
    - echo "=== Current Terraform State ==="
    - terraform init -reconfigure
    - echo "=== State List ==="
    - terraform state list || echo "No state found"
    - terraform destroy -auto-approve
    - terraform state list || echo "All resources destroyed"
  environment:
    name: production
    action: stop
  needs:
  - job: infra-plan
    artifacts: true
    optional: true
  rules:
    - when: manual
