stages:
  - build
  - docker-push
  - terraform-init
  - terraform-plan
  - terraform-apply
  - terraform-destroy

variables:
  DOCKER_REGISTRY: "docker.io"
  DOCKER_IMAGE: "$DOCKER_REGISTRY/yourusername/your-image"
  TERRAFORM_DIR: "Livrables/infra"
  DOCKER_DIR: "Livrables/app" 
  TF_VAR_image_tag: "latest" 

# Manual job to build Docker image
build_image:
  stage: build
  script:
    - echo "Building Docker image..."
    - cd $DOCKER_DIR
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_REF_NAME .
  only:
    - master
    - merge_requests
  when: manual 
docker_push:
  stage: docker-push
  script:
    - echo "Pushing Docker image to Docker Hub..."
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $DOCKER_IMAGE:$CI_COMMIT_REF_NAME
  only:
    - master
    - merge_requests
  when: manual 
  dependencies:
    - build_image  
terraform_init:
  stage: terraform-init
  script:
    - echo "Initializing Terraform..."
    - cd $TERRAFORM_DIR
    - terraform init
  only:
    - master
  when: manual  
terraform_plan:
  stage: terraform-plan
  script:
    - echo "Planning Terraform infrastructure..."
    - cd $TERRAFORM_DIR
    - terraform plan -var="image_tag=$CI_COMMIT_REF_NAME"
  only:
    - master
  when: manual 
  dependencies:
    - terraform_init

terraform_apply:
  stage: terraform-apply
  script:
    - echo "Applying Terraform infrastructure..."
    - cd $TERRAFORM_DIR
    - terraform apply -var="image_tag=$CI_COMMIT_REF_NAME" -auto-approve
  only:
    - master
  when: manual 
  dependencies:
    - terraform_plan
terraform_destroy:
  stage: terraform-destroy
  script:
    - echo "Destroying Terraform infrastructure..."
    - cd $TERRAFORM_DIR
    - terraform destroy -var="image_tag=$CI_COMMIT_REF_NAME" -auto-approve
  only:
    - master
  when: manual
  dependencies:
    - terraform_plan
